language: node_js
node_js:
 — “8”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy --only hosting — project more-thrash — token 1/aDzzd75HJd_1R2V_C0VU9wf_NEOQOvNVVQALLmLHUueOeuX21MWwQnUPuqOUOiqz.